name: Move LeetCode Solution Folders

on:
  push:
    paths:
      - '00*-*/**'

jobs:
  move-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List directory contents before moving
        run: |
          echo "Before moving:"
          ls -R

      - name: Check if ACTIONS_DEPLOY_KEY is set
        run: |
          if [ -z "${{ secrets.ACTIONS_DEPLOY_KEY }}" ]; then
            echo "ACTIONS_DEPLOY_KEY is not set"
            exit 1
          else
            echo "ACTIONS_DEPLOY_KEY is set"
          fi

      - name: Move solution folders to test directory
        run: |
          mkdir -p test
          for dir in 00*-*/; do
            if [ -d "$dir" ]; then
              mv "$dir" test/
            fi
          done

      - name: List directory contents after moving
        run: |
          echo "After moving:"
          ls -R test

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Move LeetCode solution folders to test directory"
          git push "https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/${{ github.repository }}.git" || echo "No changes to commit"
